## The context in which this server is working
context: Bukkit
## The token to authenticate in the bot
token: none
## The list of commands that can be enabled:
## - fly: allows players to fly
## - ping: allows players to see their ping
## - gamemode: allows players to change their gamemode
## - ready: when pgm is loaded players can /ready and /unready to start a match
enabled-commands:
  - fly
  - ping
  - gamemode
## The settings for certain listeners
listener-settings:
  ## Listener for saving the stats after a match
  pgm-stats:
    ## Whether to save stats
    enabled: false
  ## Listener for command executions. To print what others are doing with commands!
  command-execution:
    ## Whether this listener is enabled
    enabled: true
    ## What's the permission that allows players to see who's executing a command
    permission: guido.adminchat
    ## How is it displayed for those who posses the permission
    ## Placeholders are:
    ## %player% for the name of the player
    ## %player_display%% for the player display name
    ##  %command% for the command that the player executed
    chat: "[&6A&r] %player_display% &6executed &r%command%"
    ## Commands that are not sent
    banned:
      - tell
      - msg
  ## A listener for testing. This will print guido events
  test:
    enabled: true
  ## An anti-cheat to detect players using unfair advantages
  anti-cheat:
    ## Whether the anti-cheat is enabled
    enabled: true
    ## The delay between suspicious calls
    delay: 5s
    ## The permissions of the players that can see calls
    permission: guido.adminchat
    ## How is it displayed for those who posses the permission
    ## Placeholders are:
    ## %player% for the name of the player
    ## %player_display%% for the player display name
    ##  %reason% the reason why the player is suspicious
    chat: "[&6A&r] %player_display% &6cheats &r%reason%"
  ## Detects for auto clicking
  auto-click-detector:
    ## Whether the detector is enabled
    enabled: true
    ## The delay to which clicks and averages reset. This means how much time should
    ## take for clicks to be measured again
    reset-delay: 50
    ## The maximum cps until it starts warning the staff
    max-cps: 16.0
    ## The minimum deviation to which a player might get banned
    ## This means the difference between click speeds
    min-deviation: 0.01
  ## Detect people using reach hacks
  reach-detector:
    ## Whether this detector should be enabled
    enabled: true
  ## Whether to enable match making
  match-making:
    ## True tp enable PGM match making
    enabled: false
  ## Whether to force the players to spawn in a central location
  spawn:
    ## Whether to enable this function
    enabled: false
