 # The context in which this server is working
context: Bukkit
# The token to authenticate in the bot
token: none
# The host to connect with the bot
host: localhost
# The port to connect with the bot
port: 3366
## The list of commands that can be enabled:
## - fly: allows players to fly
## - ping: allows players to see their ping
## - gamemode: allows players to change their gamemode
## - ready: when pgm is loaded players can /ready and /unready to start a match
## - sudo: TODO
commands:
  - fly
  - ping
  - gamemode
## Config for standalone server running bot
bot:
  mongo-uri: "mongodb://localhost:27017"
  mongo-database: "guido"
  token: "https://discord.com/developers/"
  timeout: 10000
  guild: 1511402659767128291
## The settings for certain listeners
modules:
  #  <---------------------------------------------------------------------------------------->
  #                           LISTENERS THAT DO NOT REQUIRE DEPENDENCIES
  #  <---------------------------------------------------------------------------------------->
  # Listener for command executions. To print what others are doing with commands!
  command-execution:
    # Whether this listener is enabled
    enabled: true
    # What's the permission that allows players to see who's executing a command
    permission: guido.adminchat.cmd
    # How is it displayed for those who posses the permission
    # Placeholders are:
    # %player% for the name of the player
    # %player_display%% for the player display name
    #  %command% for the command that the player executed
    chat: "[&6A&r] %player_display% &6executed &r%command%"
    # Commands that are not sent
    banned:
      - tell
      - msg
  #  <---------------------------------------------------------------------------------------->
  #                             LISTENERS THAT REQUIRE PGM
  #  <---------------------------------------------------------------------------------------->
  # Listener for saving the stats after a match
  pgm-stats:
    # Whether to save stats
    enabled: false
  # Whether to enable match making
  match-making:
    # True to enable PGM match making
    enabled: false