main: com.starfishst.bukkit.GuidoPlugin
name: Guido
description: Googas core
## The version of the bot is as follows:
## major.small.patch-status-id
## The status is:
## 0 -> SNAPSHOT
version: ${project.version}
depend:
# Trim is another googas project used to create templates on any kind of server to download them from github
# added this as a dependency as that project also uses commons and easy-commands and loading those classes
# in the classpath has caused some exceptions.
# TODO this is probably not the best solution as sometimes template might not be needed
# maybe add a way of Trim loading the classes but not the plugin itself
# because right now it needs to load a template 100% of the time
  - Trim
softdepend:
  # PvpGameManager ocn plugin. The plugin is also the googas fork as Guido loads
  # groups dynamically to keep the server with all of the same
  - PGM
  # This is the fork of googas of the plugin to create events of ocn
  - Events
  # ProtocolLib is a library to easily use minecraft packets this is the latest version of
  # the plugin, no fork needed.
  - ProtocolLib