main: com.starfishst.bukkit.GuidoPlugin
name: Guido
description: An implementation for the Guido bot to use PGM
## The version of the bot is as follows:
## major.small.patch-status-id
## The status is:
## 0 -> SNAPSHOT
version: ${project.version}
softdepend:
  - PGM