main: com.starfishst.guido.pgm.GuidoPlugin
name: Guido
description: An implementation for the GuidoPlugin bot to use PGM
## The version of the bot is as follows:
## major.small.patch-status-id
## The status is:
## 0 -> SNAPSHOT
version: 1.0.0-0-1