##############################################################################################
##                                                                                                                                                                                      #
## To use special characters you must use https://en.wikipedia.org/wiki/List_of_Unicode_characters as          #
## Properties files are not UTF_8                                                                                                                                 #
##                                                                                                                                                                                      #
##############################################################################################
## Required for loading
lang=en
# This unicode is used for users to change their language
unicode=U+1F1ECU+1F1E7

## Framework stuff required for commands
invalid.number=%string% is not a number!
invalid.double=%string% is not a decimal!
invalid.double-empty=Decimals cannot be empty!
invalid.boolean=%string% is not a boolean!
invalid.time=%string% is not a valid time!
invalid.user=%string% is not an user!
invalid.member=%string% is not a member!
invalid.role=%string% is not a role!
invalid.channel=%string is not a channel!
invalid.strings=Your are missing %missing% strings in %name%!
missing-argument=You are missing %name% (%description%) in the position %position%
command-not-found=%name% is not a command!
not-allowed=You are not allowed to use this command!
guild-only=this command may only be executed inside a Discord guild!
cooldown=You may not use this command in the next %cooldown%
# Footer for every embed
footer=Googas Network 2020

## Titles for command embeds
title.unknown=Unknown error!
title.permission=Missing permission!
title.generic=Done!
title.usage=Wrong usage!
title.error=An error has happened!
response=%title% -> %description%
# The thumbnail to use in embeds
thumbnail-url=

## Commands

# Eval command
eval.desc=Executes java script code
eval.code=Code
eval.code.desc=The code to execute

# Stop command
stop.desc=Stops the bot

# Lang command
lang.desc=Change your language
lang.change=Change your language. \n :flag_es: Para cambiar al español \n :flag_fr: Pour le changer en francais

# Teams commands
teams.desc=Get two teams from the voice chat you are connected
teams.result=Team 1: %team1% \n Team 2: %team2%
teams.not-event=There's not an event amount of players in the voice chat!
teams.not-connected=You are not connected to a voice chat

# Leaders commands
leaders.desc=Get a number of leaders in the voice channel
leaders.number=Number
leaders.number.desc=The number of leaders to get
leaders.result=The leaders are: %leaders%
leaders.not-enough=There's not enough players to get %number% of leaders
leaders.not-connected=You are not connected to a voice chat

# Token commands
token.desc=See your generated or someone else's tokens

# Token generation commands
token.gen.desc=Generate a new token!
token.gen.perm=Permission
token.gen.perm.desc=The level of permission for the token: `read` `read_write`