##############################################################################################
##                                                                                                                                                                                      #
## To use special characters you must use https://en.wikipedia.org/wiki/List_of_Unicode_characters as          #
## Properties files are not UTF_8                                                                                                                                 #
##                                                                                                                                                                                      #
##############################################################################################
## Required for loading
lang=en
# This unicode is used for users to change their language
unicode=U+1F1ECU+1F1E7

## Framework stuff required for commands
invalid.number=%string% is not a number!
invalid.double=%string% is not a decimal!
invalid.double-empty=Decimals cannot be empty!
invalid.boolean=%string% is not a boolean!
invalid.time=%string% is not a valid time!
invalid.user=%string% is not an user!
invalid.member=%string% is not a member!
invalid.role=%string% is not a role!
invalid.channel=%string is not a channel!
invalid.strings=Your are missing %missing% strings in %name%!
invalid.ladder=%string% is not a valid ladder
missing-argument=You are missing %name% (%description%) in the position %position%
command-not-found=%name% is not a command!
not-allowed=You are not allowed to use this command!
guild-only=this command may only be executed inside a Discord guild!
cooldown=You may not use this command in the next %cooldown%
# Footer for every embed
footer=Googas Network 2020

## Titles for command embeds
title.unknown=Unknown error!
title.permission=Missing permission!
title.generic=Done!
title.usage=Wrong usage!
title.error=An error has happened!
response=%title% -> %description%
# The thumbnail to use in embeds
thumbnail-url=

## Commands providers

# Bot user provider
not-linked=%mention% does not have a linked account

## Commands

# Eval command
eval.desc=Executes java script code
eval.code=Code
eval.code.desc=The code to execute

# Stop command
stop.desc=Stops the bot

# Lang command
lang.desc=Change your language
lang.change=Change your language. \n :flag_es: Para cambiar al español \n :flag_fr: Pour le changer en francais

# Teams commands
teams.desc=Get two teams from the voice chat you are connected
teams.result=Team 1: %team1% \n Team 2: %team2%
teams.not-event=There's not an event amount of players in the voice chat!
teams.not-connected=You are not connected to a voice chat

# Leaders commands
leaders.desc=Get a number of leaders in the voice channel
leaders.number=Number
leaders.number.desc=The number of leaders to get
leaders.result=The leaders are: %leaders%
leaders.not-enough=There's not enough players to get %number% of leaders
leaders.not-connected=You are not connected to a voice chat

# Token commands
tokens.desc=See your generated or someone else's tokens
tokens.empty=You don't seem to have tokens
tokens.token= \n %token% level: %level%

# Token generation commands
token.gen.desc=Generate a new token!
token.gen.perm=Permission
token.gen.perm.desc=The level of permission for the token: `read` `read_write`

# Help command
help.desc=Get help on how to use certain commands
help.cmd=Command
help.cmd.desc=The command to get help from
help.not-allowed=You are not allowed to see help for the command %name%
help.unknown-cmd=The command %name% does not allowed

help.cmd.title=Seeing information for %name% \n Description: `%desc%` \n Aliases: `%aliases%` \n Permission: `%perm%`
help.cmd.empty-node=No permission
help.cmd.arg.required= <%name%>
help.cmd.arg.optional= (%name%)
help.cmd.usage=\n Usage: `.%name% %arguments%`

help.parent-cmd.child= \n - %name% `%desc%`
help.parent.children=\n Children: %children%

help.cmds.title=You're getting help for the commands. To see the information for an specific command use: `.help <command name>`
help.cmds=\n - %name% `%desc%`

# Links command
links.desc=See the links which your account has
links.title=**Seeing links for %id%**
links.empty=%id% does not have linked accounts
link.invalid=Invalid link
link.discord-guild=\n > Inside discord server: %mention% in %guild%
link.discord=\n > Discord: %mention%
link.minecraft=\n > Minecraft: %nickname%

# Match commands
match.desc=Save manually a match. Giving the elo, win and lose manually
match.ladder=Ladder
match.ladder.desc=The ladder where the match occurred
match.mention-one=You must mention at least one member!
match.different-than-required=The number of given member is %given% when the ladder expects %expected%
match.saved=Match has been saved with the id %id%

# Multiplier commands
multipliers.desc=See all the multipliers that the guild has
multipliers.page=Page
multipliers.page.desc=The page of multipliers to see
multipliers.empty=There hasn't been multipliers set yet
multipliers.title=Seeing multipliers: **%page%**/%max%
multipliers.multiplier=\n %name% _value_: `%value%`

# Subcommand set

multi.set.desc=Set the value of certain multiplier
multi.set.name=Name
multi.set.name.desc=The name of the multiplier
multi.set.value=Value
multi.set.value.desc=The new value of the multiplier
multi.set.success=%name% value has been set to: `%value%`

# Subcommand delete

multi.delete.desc=Delete a multiplier
multi.delete.name=Name
multi.delete.name.desc=The name of the multiplier to delete
multi.delete.success=%name% multiplier has been deleted
multi.delete.not-exists=%name% multiplier does not exist

# Ladders command
ladders.desc=See all the ladders in the guild
ladders.page=Page
ladders.page.desc=The page of ladders to see
ladders.empty=There's no ladders
ladders.title=Seeing ladders: **%page%**/%max%
ladders.ladder=\n _%name%_ base: `%base%` players per team: `%players%`

# Create subcommand
ladders.make.desc=Create a new ladder
ladders.make.name=Name
ladders.make.name.desc=The name of the new ladder
ladders.make.players=Players
ladders.make.players.desc=The number of players per team in the ladder
ladders.make.base=Base
ladders.make.base.desc=The base value of the ladder for every player
ladders.make.success=The ladder `%name%` has been created
ladders.make.exists=The ladder `%name%` already exists

# Delete subcommand
ladders.del.desc=Delete certain ladder
ladders.del.name=Name
ladders.del.name.desc=The name of the ladder to delete
ladders.del.not-exists=The ladder %name% does not exist
ladders.del.success=The ladder %name% has been deleted