##############################################################################################
##                                                                                                                                                                                      #
## To use special characters you must use https://en.wikipedia.org/wiki/List_of_Unicode_characters as          #
## Properties files are not UTF_8                                                                                                                                 #
##                                                                                                                                                                                      #
##############################################################################################
## Required for loading
lang=en
# This unicode is used for users to change their language
unicode=U+1F1ECU+1F1E7

## Framework stuff required for commands
invalid.number=`%string%` is not a number!
invalid.double=`%string%` is not a decimal!
invalid.boolean=`%string%` is not a boolean!
invalid.time=`%string%` is not a valid time!
invalid.user=`%string%` is not an user!
invalid.member=`%string%` is not a member!
invalid.role=`%string%` is not a role!
invalid.channel=`%string` is not a channel!
invalid.strings=Here's some help for you to complete the command correctly, you can also use `.help`: \n You are missing the argument `%name%` in the position `%position%`. \n ***What is it?*** \n %description%
invalid.ladder=`%string%` is not a valid ladder
invalid.match=`%string%` is not a valid match id
invalid.team=`%string%` is not a valid team
invalid.minecraft=`%string%` is not a valid minecraft player
invalid.link=`%string%` is not a valid link entity!
missing-argument=Here's some help for you to complete the command correctly, you can also use `.help`: \n You are missing the argument `%name%` in the position `%position%`. \n ***What is it?*** \n %description%
command-not-found=`%name%` is not a command! \n You can check all the commands using `.help`
not-allowed=You are not allowed to use this command. \n If you believe this is an error please contact the support matchTeam.
guild-only=This command may only be executed in the [Googas Discord server](https://discord.io/GOOGAS) \n If you haven't joined we will be more that happy to have you! https://discord.io/GOOGAS
cooldown=Please wait `%cooldown%` to execute this command again.
# Footer for every embed
footer=Googas Network 2020 - googas.me

## Titles for command embeds
title.unknown=Unexpected error
title.permission=Missing permission
title.generic=Done
title.usage=Incorrect command execution
title.error=There's been an error
response=%title% -> %description%
# The thumbnail to use in embeds
thumbnail-url=https://cdn.discordapp.com/avatars/591482187031773225/1ad074d29dd72f9a8a634382e68ef4ad.png

## Commands providers

# Bot user provider
not-linked=%mention% does not have a linked account

## Commands

# Eval command
eval.desc=Execute javascript code
eval.code=Code
eval.code.desc=The javascript code to execute. \n When using the return statement I will send you a message with the returned object. For example: \n ```return 4 + 4``` I will print: `Script has been executed 2` \n I will provide you with objects such as: \n "_message_" The message that was used to execute this command \n "_channel_" The channel where this command was executed \n "_args_" An array of **string** which are the representation of this command execution \n "_api_" My connection with the **Discord API** \n > In case that the command is executed inside a guild (Discord server) I will also provide the next objects: \n "_guild_" which is the guild where the command was executed \n "_member_" You! This is the user who executes the command

# Stop command
stop.desc=Stops the bot

# Lang command
lang.desc=Change your language. At the moment this feature is not fully implemented as we are looking for @translators to extend the bot language!
lang.change=Change your language. \n :flag_es: Para cambiar al español \n :flag_fr: Pour le changer en francais

# Teams commands
matchTeams.desc=Get two matchTeams from the voice chat you are connected. This will divide the members of the channel in two groups with an equal size
matchTeams.result=Team 1: %team1% \n Team 2: %team2%
matchTeams.not-event=To divide in a equal size of groups it is **required** to have an **even** amount of users connected to the voice channel.
matchTeams.not-connected=You must connect to a voice channel before executing this command

# Leaders commands
leaders.desc=Get the given number of random users from the voice channel to represent as captains!
leaders.number=Number
leaders.number.desc=Examples: \n ```.leaders 1``` \n Will return one captain \n ```.leaders 5``` \n Will return 5 captains \n > There must be more or an equal amount of users connected to the channel too!
leaders.result=The leaders are: %leaders%
leaders.not-enough=There's not enough players to get `%number%` of leaders
leaders.not-connected=You must connect to a voice channel before executing this command

# Token commands
tokens.desc=See your or someone else's generated tokens. \n **Tokens must be kept secret, please don't execute this command in public channels**
tokens.empty=You haven't generated tokens yet. \n Check `.help tokens` to know how to generate them
tokens.token= \n `%token%` Level: `%level%`

# Token generation commands
token.gen.desc=Generate a new token! \n **Tokens must be kept secret, please don't execute this command in public channels**
token.gen.perm=Permission
token.gen.perm.desc=The level of permission for the token: \n Depending on your permissions you can generate: `read`, `read_write` or `administrative`

# Help command
help.desc=Get help and information on how to use certain commands. If you need any other kind of help please contact support
help.cmd=Command
help.cmd.desc=The command to get help from. \n For example `.help help` Yes, it can be used for any command. Children command are not fully supported yet.
help.not-allowed=You are not allowed to see help for the command %name%. If you believe this is an error please contact support
help.unknown-cmd=The command `%name%` does not exist

help.cmd.title=Seeing information for ***%name%*** \n Description and Help: \n `%desc%` \n Aliases: `%aliases%` \n Permission: `%perm%`
help.cmd.empty-node=No permission
help.cmd.arg.required= <%name%>
help.cmd.arg.optional= (%name%)
help.cmd.usage=\n Usage: \n > <> Means that the argument is required \n > () Means that the argument is optional > You don't have to use `()` or `<>` in the command execution \n `.%name% %arguments%`

help.parent-cmd.child= \n - %name% `%desc%`
help.parent.children=\n Children: \n This commands are executed as follows: `.<parent> <child> arguments...` \n %children%

help.cmds.title=You're getting help for the commands. \n If you require further help please contact the support matchTeam \n To see the information for an specific command use: `.help <command>`
help.cmds=\n - .%name% `%desc%`

# Links command
links.desc=See the links which your account has. Links will also include Discord Accounts
links.title=**Seeing links for %id%**
links.empty=`%id%` does not have linked accounts
link.invalid=\n Invalid link. This can be caused because it cannot be reached
link.discord=\n > Discord: %mention%
link.minecraft=\n > Minecraft: %nickname%

# Link command
link.code=Code
link.code.desc=The code given to link your account. This code has a length of four digits and it is case sensitive!
link.code-not-match=Your code does not match a link query. Please check your code! Please not that it is case sensitive!
link.data-not-found=Your data could not be linked. This may be because of an internal error. Please contact the support matchTeam
link.only-one=You may only have one `%type%` link!
link.added=You've linked your account to: %readable%

# Match commands
match.desc=Save manually a match. Giving the elo, win and lose manually
match.ladder=Ladder
match.ladder.desc=The ladder where the match occurred. To see all the available ladders use `.ladders`
match.participants=Participants
match.participants.desc=The participants of the match
match.mention-one=You must mention at least one participant
match.different-than-required=The number of given participants is `%given%` when the ladder expects `%expected%`
match.saved=Match has been saved with the id `%id%`

# Ladders command
ladders.desc=See all the ladders in the guild
ladders.page=Page
ladders.page.desc=The page of ladders to see
ladders.empty=There's no ladders
ladders.title=Seeing ladders: **%page%**/%max%
ladders.ladder=\n _%name%_ base: `%base%` players per matchTeam: `%players%`

# Create subcommand
ladders.make.desc=Create a new ladder
ladders.make.name=Name
ladders.make.name.desc=The name of the new ladder
ladders.make.players=Players
ladders.make.players.desc=The number of players per matchTeam in the ladder
ladders.make.base=Base
ladders.make.base.desc=The base value of elo of the ladder for every player
ladders.make.success=The ladder `%name%` has been created
ladders.make.exists=The ladder `%name%` already exists

# Delete subcommand
ladders.del.desc=Delete certain ladder
ladders.del.name=Name
ladders.del.name.desc=The name of the ladder to delete
ladders.del.not-exists=The ladder `%name%` does not exist
ladders.del.success=The ladder `%name%` has been deleted

# Edition subcommands
ladder.edit.ladder=Ladder
ladder.edit.ladder.desc=The name of the ladder to edit. You can see all the available ladders using `.ladder`
ladder.edit.key=Key
ladder.edit.key.desc=The key that represents the value
ladder.edit.value=Value
ladder.edit.value.desc=The value to set
ladder.edit.string=Edit a string option for the ladder
ladder.edit.integer=Edit an integer option for the ladder
ladder.edit.double=Edit a double option for the ladder
ladder.edit.result=`%key%` has been changed to `%value%`

## Match information
match.title=Seeing match %id%
match.description=Use the command `.game %id%` to see information about this match
match.announce.title=Match %id% has finished!
match.team=\n %name% members: %members%

# Game command
game.desc=See the information about a match
game.not-found=The game `%id%` was not found

# Range command
range.desc=See the range of certain role. Ranges are the minimum and maximum elo in which a role is given
range.role=Role
range.role.desc=The role to see the range of
range.no-range=%mention% does not have a range assigned
range.range=%mention% has the range for `%ladder%` is from %min% to %max%

# Set subcommand
range.set=Set the range for certain role
range.set.role=Role
range.set.role.desc=The role to set the range to
range.set.ladder=Ladder
range.set.ladder.desc=The ladder that the range will apply to. To see all available ladders use `.ladders`
range.set.min=Min
range.set.min.desc=The minimum value of the range
range.set.max=Max
range.set.max.desc=The maximum value of the range
range.set.success=The range in the ladder `%ladder%` from %min% to %max% has been applied to %mention%

# Delete subcommand
range.del.desc=Delete certain range
range.del.role=Role
range.del.role.desc=The role to delete the range from
range.del.success=The range for %mention% has been deleted
range.del.not-found=%mention% does not have a range

# Queue commands
queue.desc=Join a queue and start to play. This command requires you to be connected to a voice channel.
queue.ladder=Ladder
queue.ladder.desc=The ladder to join the queue. You can see all available ladders using `.ladders` \n > To see who's waiting in the queue for this ladder use `.iq <ladder>` or `.inQueue <ladder>`
queue.already-playing=You are already playing a match, finish it before queueing again
queue.join-voice=Before joining a queue join a voice channel first
queue.failed=There's been an error while trying to join the queue. I sent you a private message with the reason of this error. If you haven't received anything check your privacy setting or it might be an internal error.
queue.success=You've joined the queue
queue.already=You're already queueing

## Categories command
categories.desc=See all the categories that have been set in the server
categories.empty=There hasn't been categories set in `%name%`
categories.title=Seeing categories for `%name%`
categories.category= \n %key% -> `%name%`

# Set subcommand
categories.set.desc=Set the category for the given key
categories.set.key=Key
categories.set.key.desc=The key to append the category
categories.set.unset=The category in `%key%` has been removed
categories.set.success=The category in `%key%` has been set to `%name%`

## Channels command
channels.desc=See all the channels that have been set in the server
channels.empty=There hasn't been channels set in %name%
channels.title=Seeing channels for %name%
channels.category= \n %key% -> `%name%`

# Set subcommand
channels.set.desc=Set the channel for the given key
channels.set.key=Key
channels.set.key.desc=The key to append the channel
channels.set.success=The channel in `%key%` has been set to `%name%`


## Finish command
finish.desc=Finish a match
finish.match=Match
finish.match.desc=The id of the match to finish
finish.winners=Winners
finish.winners.desc=The winners of the match given by the name of the matchTeam
finish.already=The match `%id%` is finished
finish.finished=The match `%id%` has been finished
finish.invalid-matchTeam=The matchTeam `%matchTeam%` in the match `%id%` was not found
finish.invalid-guild=The match `%id%` is not valid for this guild!

## Currently command
currently.desc=Get where you or someone else is playing
currently.else=Else
currently.else.desc=Who else do you want to see where is playing
currently.empty=%single% is not playing any match
currently.success=%single% is currently playing in `%matches%`

## Leader board command
lb.desc=See the leader
lb.ladder=Ladder
lb.ladder.desc=The ladder to see the leaderboard
lb.page=Page
lb.page.desc=The page of the leaderboard to see
lb.title=Seeing leaderboard for **%ladder%** \n ***%page%***/_%max%_
lb.entry=\n %index%. %single% Elo: `%elo%` Wins: `%wins%` Loses: `%loses%`
lb.not-global=You cannot see the leaderboard for global ladder

## In queue command
iq.ladder=Ladder
iq.ladder.desc=The ladder to see who's queueing. To see all available ladders use `.ladders`
iq.empty=There's no people queuing in %ladder%
iq.title=Queuing for `%ladder%` are:

## Rank command
table.desc=See the leaderboard in certain stat
table.stat=Stat
table.stat.desc=The stat to see the leaderboard
table.page=Page
table.page.desc=The page to see the leaderboard on
table.title=Seeing leaderboard for the stat **%stat%** \n ***%page%***/_%max%_
table.entry=\n %index%. %single% stat: `%stat%`

## VoiceChannel commands
vc.desc=See the voice channels set in the server
vc.empty=There's no voice channels set
vc.title=Seeing voice channels for `%name%`
vc.channel=\n `%key%`: `%name%`

# Set subcommand
vc.set.desc=Set the voice channel for the desired key
vc.set.key=Key
vc.set.key.desc=The key to set the channel
vc.set.success=`%key%` voice channel has been set to `%name%`
vc.set.connect=Please connect to a voice channel first

# Stats command
guido.stats.desc=See yours or another player stats!
stats.name=Nickname
stats.name.desc=The name of the player to see the stats
stats.player-not-found=The player %nick% was not found
stats.not-linked=You haven't linked a **minecraft account**
stats.desc=Seeing stats for %nick%
stats.title=%nick%'s stats

# Messages sent in queue
pgm-queue.no-bungee=There's no connection with the `googas.me` server. It might be closed
pgm-queue.internal=There's been an internal error while adding you to the queue
pgm-queue.internal-not-check=There's been an internal error while adding you to the queue. Could not check if you are connected to the minecraft server
pgm-queue.link-first=You must link a Minecraft account before queueing
pgm-queue.join-server=You have to be in the googas server before joining the queue: **googas.me**