## Translated by Xinoooo
lang=fr
unicode=U+1F1EBU+1F1F7

invalid.number=%string% c'est pas un numéro!
invalid.double=%string% c'est pas un décimal!
invalid.double-empty=Les decimaux peuvent pas être vides!
invalid.boolean=%string% c'est pas un boolean!
invalid.time=%string% c'est pas un temp valide!
invalid.user=%string% c'est pas un utilisateur!
invalid.member=%string% c'est pas un membre!
invalid.role=%string% c'est pas un rol!
invalid.channel=%string c'est pas un canal!
missing-argument=Il te manque %name% (%description%) en position %position%
command-not-found=%name% n'existe pas!
footer=Radiator Springs

title.unknown=Erreur inconnue!
title.permission=Erreur de permis!
title.generic=Voilá!
title.usage=Utilisation incorrecte!
title.error=Il y a une erreur!
response=%title% -> %description%
thumbnail-url=

not-allowed=T'as pas de permis d'utiliser cette commande
guild-only=Cette commande peut être utilisé seulement dans un serveur de discord!
cooldown=Tu peux utiliser cette commande dans: %cooldown%

cmd.lang=Changez votre langue. \n :flag_es: Para cambiar al español \n :flag_gb: To change to english

cmd.matchTeams.desc=
cmd.matchTeams.result=Team 1: %team1% \n Team 2: %team2%
cmd.matchTeams.not-event=
cmd.matchTeams.not-connected=

cmd.leaders.desc=Get a number of leaders in the voice channel
cmd.leaders.param.number.name=
cmd.leaders.param.number.desc=
cmd.leaders.result=
cmd.leaders.not-enough=
cmd.leaders.not-connected=