services:
  bukkit-minecraft:
    image: eclipse-temurin:25-jre
    working_dir: /server
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    volumes:
      - .:/server
    command: java -jar custom.jar
    networks:
      - mongo-net

networks:
  mongo-net:
    external: true
