lang=es
unicode=U+1F1EAU+1F1F8

invalid.number=%string% no es un numero!
invalid.double=%string% no es un decimal!
invalid.double-empty=Los decimales no pueden estar vacios!
invalid.boolean=%string% no es un boolean!
invalid.time=%string% no es un tiempo valido!
invalid.user=%string% no es un usuario!
invalid.member=%string% no es un miembro!
invalid.role=%string% no es un rol!
invalid.channel=%string no es un canal!
missing-argument=Te falta %name% (%description%) en la posicion %position%
command-not-found=%name% no existe!
footer=Radiator Springs

title.unknown=Error desconocido!
title.abstractPermission=Error de permisos!
title.generic=Hecho!
title.usage=Uso incorrecto!
title.error=Un error ha ocurrido!
response=%title% -> %description%
thumbnail-url=

not-allowed=No tienes permitido usar este comando
guild-only=Este comando solo puede ser usado dentro de un servidor de Discord!
cooldown=No puedes usar este comando hasta dentro de: %cooldown%

cmd.lang=Cambia tu lenguaje. \n :flag_gb: To change to english \n :flag_fr: Pour le changer en francais

cmd.matchTeams.desc=Divide entre dos los jugadores conectados en tu canal de voz
cmd.matchTeams.result=Team 1: %team1% \n Team 2: %team2%
cmd.matchTeams.not-event=No hay jugadores pares
cmd.matchTeams.not-connected=No estas conectado a un canal de voz

cmd.leaders.desc=Consigue un numero de capitanes desde el voice channel
cmd.leaders.param.number.name=Numero
cmd.leaders.param.number.desc=El numero de capitanes para conseguir
cmd.leaders.result=Los capitanes son: %leaders%
cmd.leaders.not-enough=No hay suficientes jugadores para conseguir %numero% de capitan(es)
cmd.leaders.not-connected=No estas conectado a un canal de voz