package me.googas.api.loader;

import java.util.Collection;
import java.util.UUID;
import lombok.NonNull;
import me.googas.api.token.AuthToken;

public interface TokenLoader extends DataLoader {
  /**
   * Get an auth token using its unique string
   *
   * @param token the unique string of the token
   * @return the token if found else null
   */
  AuthToken getAuthToken(@NonNull String token);

  /**
   * Get the tokens from a user id
   *
   * @param user the user to getId the tokens from
   * @return the tokens generated by a user
   */
  @NonNull
  Collection<AuthToken> getTokens(@NonNull UUID userId);
}
