package me.googas.api.loader;

import java.util.Collection;
import java.util.Optional;
import java.util.UUID;
import lombok.NonNull;
import me.googas.api.token.AuthLevel;
import me.googas.api.token.AuthToken;

public interface TokenLoader extends DataLoader {
  /**
   * Get an auth token using its unique string
   *
   * @param token the unique string of the token
   * @return the token if found else null
   */
  @NonNull
  Optional<? extends AuthToken> getAuthToken(@NonNull String token);

  /**
   * Get the tokens from a user id
   *
   * @param user the user to getId the tokens from
   * @return the tokens generated by a user
   */
  @NonNull
  Collection<? extends AuthToken> getTokens(@NonNull UUID userId);

  @NonNull
  AuthToken create(@NonNull UUID id, @NonNull AuthLevel level);
}
